export const mappedData = {
  'AAAA': {
    title: 'NPO 企劃',
    traits: ['開放型','盡責型','外向型','親和型','沉穩型'],     
    summary: '這些特質使您適合擔任NPO企劃，因為您具有創造性、負責任、善於溝通並能有效協作。',
    backgroundImg: 'v1/FJUPSY/result/AAAA_background',
    podcastImg: 'v1/FJUPSY/result/AAAA_podcast',
    podcastUrl: 'https://open.firstory.me/story/cl46yjyft00b101zg21s35kwj/platforms',
  },
  'AAAB': {
    title: '產品經理',
    traits: ['卓越的溝通技巧','分析能力','領導潛力'],     
    summary: '這使您非常適合擔任產品經理。您能夠協調不同團隊，理解客戶需求並制定有效的產品策略。',
    backgroundImg: 'v1/FJUPSY/result/AAAB_background',
    podcastImg: 'v1/FJUPSY/result/AAAB_podcast',
    podcastUrl: 'https://open.firstory.me/story/clbhcf8co00in01s06hhfdcwk/platforms',
  },
  'AABA': {
    title: '關懷訪視員',
    traits: ['同理心','耐心','溝通能力'],     
    summary: '非常適合擔任關懷訪視員。您將能夠關心並支持需要幫助的人，並建立有意義的人際關係。',
    backgroundImg: 'v1/FJUPSY/result/AABA_background',
    podcastImg: 'v1/FJUPSY/result/AABA_podcast',
    podcastUrl: 'https://open.firstory.me/story/clrt7i97f00ls01xs2la3bhbu/platforms',
  },
  'AABB': {
    title: '業務',
    traits: ['溝通能力強','人際關係良好','積極進取的特質'],     
    summary: '非常適合擔任業務職位。您的說服力和抗壓性也是業務工作所需的優點。',
    backgroundImg: 'v1/FJUPSY/result/AABB_background',
    podcastImg: 'v1/FJUPSY/result/AABB_podcast',
    podcastUrl: 'https://open.firstory.me/story/cl3v977bc00fq01xd2ddu7f7w/platforms',
  },
  'ABAA': {
    title: '輔導老師',
    traits: ['對人感興趣且關懷別人', '身心成熟',  '自我了解', '肯定自我', '真誠的態度'],
    summary: '這些特質將有助於您在輔導工作中建立良好的連結，並幫助學生克服困難，實現個人成長。',
    backgroundImg: 'v1/FJUPSY/result/ABAA_background',
    podcastImg: 'v1/FJUPSY/result/ABAA_podcast',
    podcastUrl: 'https://open.firstory.me/story/cls9quqap00c801ut6fk21sdk/platforms',
  },
  'ABAB': {
    title: '人力資源',
    traits: ['敏銳的觀察力', '良好的溝通能力', '心理素質強大', '邏輯與企劃能力', '保持開放心態'],     
    summary: '這些特質將有助於你在人力資源管理領域中取得成功！',
    backgroundImg: 'v1/FJUPSY/result/ABAB_background',
    podcastImg: 'v1/FJUPSY/result/ABAB_podcast',
    podcastUrl: 'https://open.firstory.me/story/clqx6trxz03ny01ruaqyuhuvb/platforms',
  },
  'ABBA': {
    title: '咖啡店老闆',
    traits: ['熱情與親和力','創意與創新','耐心和細心','對品質的追求'],     
    summary: '總之，您具備了成為一位出色咖啡店老闆所需的特質！',
    backgroundImg: 'v1/FJUPSY/result/ABBA_background',
    podcastImg: 'v1/FJUPSY/result/ABBA_podcast',
    podcastUrl: 'https://open.firstory.me/story/cl6ho3dsr023d01xkefocfbfu/platforms',
  },
  'ABBB': {
    title: '觀護人',
    traits: ['耐心','同理心','細心','溝通能力'],     
    summary: '作為觀護人，你將能夠關心並照顧他人，並在需要時提供支持和協助。',
    backgroundImg: 'v1/FJUPSY/result/ABBB_background',
    podcastImg: 'v1/FJUPSY/result/ABBB_podcast',
    podcastUrl: 'https://open.firstory.me/story/clf0l04nw01w901vw7mt61x33/platforms',
  },
  'BAAA': {
    title: 'Podcaster',
    traits: ['語言表達能力','好奇心','研究能力','聆聽技巧','創意思維'],     
    summary: '',
    backgroundImg: 'v1/FJUPSY/result/BAAA_background',
    podcastImg: 'v1/FJUPSY/result/BAAA_podcast',
    podcastUrl: 'https://open.firstory.me/story/clbmymwdc059r01s03a8a3act/platforms',
  },
  'BAAB': {
    title: '電商老闆',
    traits: ['強烈的欲望','忍耐力','開闊的眼界','商業敏感性','人脈拓展','謀略思維'],     
    summary: '',
    backgroundImg: 'v1/FJUPSY/result/BAAB_background',
    podcastImg: 'v1/FJUPSY/result/BAAB_podcast',
    podcastUrl: 'https://open.firstory.me/story/cl1ha3krg00mc0h3n5rttfkle/platforms',
  },
  'BABA': {
    title: '心理師',
    traits: ['敏銳的洞察力','同理心','聆聽並理解人們的情感和內心世界'],     
    summary: '透過溝通和治療技巧，我能幫助他們面對挑戰、克服困難，並找到內在的平衡與成長。',
    backgroundImg: 'v1/FJUPSY/result/BABA_background',
    podcastImg: 'v1/FJUPSY/result/BABA_podcast',
    podcastUrl: 'https://open.firstory.me/story/clqyrz01p00m401ur94bx7q9n/platforms',
  },
  'BABB': {
    title: 'UI設計師',
    traits: ['敏銳的洞察力','同理心','聆聽並理解人們的情感和內心世界'],     
    summary: '這些特質使你能成為一位優秀的UI設計師，能夠創造出令人驚艷的用戶界面。',
    backgroundImg: 'v1/FJUPSY/result/BABB_background',
    podcastImg: 'v1/FJUPSY/result/BABB_podcast',
    podcastUrl: 'https://open.firstory.me/story/cl1yk8t7z0esp01w801su0140/platforms',
  },
  'BBAA': {
    title: '公務員',
    traits: ['條理性','細心','適法性','穩定性','責任感'],     
    summary: '',
    backgroundImg: 'v1/FJUPSY/result/BBAA_background',
    podcastImg: 'v1/FJUPSY/result/BBAA_podcast',
    podcastUrl: 'https://open.firstory.me/story/claz0qbrs03zc01xa2dgh64ru/platforms',
  },
  'BBAB': {
    title: '數據分析師',
    traits: ['觀察力','注意細節','商務敏銳度','簡單講故事','溝通協調能力','持續學習'],     
    summary: '',
    backgroundImg: 'v1/FJUPSY/result/BBAB_background',
    podcastImg: 'v1/FJUPSY/result/BBAB_podcast',
    podcastUrl: 'https://open.firstory.me/story/cl52fatky02pb01x6be45doup/platforms',
  },
  'BBBA': {
    title: '芳療師',
    traits: ['熱忱與同理心','專業知識與技能','整合和應用能力','堅定的學習態度'],     
    summary: '作為芳療師，您將能幫助人們在身心靈上放鬆，並改善其健康與幸福感。',
    backgroundImg: 'v1/FJUPSY/result/BBBA_background',
    podcastImg: 'v1/FJUPSY/result/BBBA_podcast',
    podcastUrl: 'https://open.firstory.me/story/clnnuzvq4001101x2cq444vag/platforms',
  },
  'BBBB': {
    title: '身心靈工作者',
    traits: ['敏感性','同理心','創意'],     
    summary: '這使您適合擔任身心靈工作者。您能夠理解他人的情感和需求，並以創新的方式提供支持和指導。',
    backgroundImg: 'v1/FJUPSY/result/BBBB_background',
    podcastImg: 'v1/FJUPSY/result/BBBB_podcast',
    podcastUrl: 'https://open.firstory.me/story/clht3pfg2006101x817ij34o4/platforms',
  }
}